### ISSUE TITLE
4 tests fail with 1.10.0

### ISSUE THREAD

**Issue by heirecka** [nih-at/libzip#386] opened 2023-06-25 21:12 UTC
**Describe the Bug**

4 tests stated to fail with 1.10.0, compared to 1.9.2
```
 19/165 Test  #19: cancel_45.test ...................................***Failed    0.04 sec
output differs:
-0.0% done
-25.0% done
-50.0% done
error output differs:
-can't close zip archive 'test.zip': Operation cancelled
+invalid option -- '1'
+/home/heiko/Quelltexte/git-sources/miscellaneous/libzip/build/regress/ziptool_regress [-ceghnrst] [-Hmx] [-F fragment-size] [-l len] [-o offset] archive command1 [args] [command2 [args] ...]
+invalid option -1
cancel_45 -- FAIL: output, error output

        Start  20: cancel_90.test
 20/165 Test  #20: cancel_90.test ...................................***Failed    0.05 sec
output differs:
-0.0% done
-25.0% done
-50.0% done
-75.0% done
-100.0% done
error output differs:
-can't close zip archive 'test.zip': Operation cancelled
+invalid option -- '1'
+/home/heiko/Quelltexte/git-sources/miscellaneous/libzip/build/regress/ziptool_regress [-ceghnrst] [-Hmx] [-F fragment-size] [-l len] [-o offset] archive command1 [args] [command2 [args] ...]
+invalid option -1
cancel_90 -- FAIL: output, error output

       Start  30: cm-default.test
 30/165 Test  #30: cm-default.test ..................................***Failed    0.04 sec
exit code differs:
-0
+1
error output differs:
+invalid option -- '1'
+/home/heiko/Quelltexte/git-sources/miscellaneous/libzip/build/regress/ziptool_regress [-ceghnrst] [-Hmx] [-F fragment-size] [-l len] [-o offset] archive command1 [args] [command2 [args] ...]
+invalid option -1
file list differs:
 large-uncompressible
-test.zip
cm-default -- FAIL: exit code, error output, file list

        Start 113: progress.test
113/165 Test #113: progress.test ....................................***Failed    0.05 sec
exit code differs:
-0
+1
output differs:
-0.0% done
-25.0% done
-50.0% done
-75.0% done
-100.0% done
error output differs:
+invalid option -- '1'
+/home/heiko/Quelltexte/git-sources/miscellaneous/libzip/build/regress/ziptool_regress [-ceghnrst] [-Hmx] [-F fragment-size] [-l len] [-o offset] archive command1 [args] [command2 [args] ...]
+invalid option -1
file list differs:
 large-uncompressible
-test.zip
progress -- FAIL: exit code, output, error output, file list
```

**libzip Version**
1.10.0

**Operating System**
Linux

I also noticed that the CI doesn't seem to run the tests for Ubuntu, when I wanted to check if tests pass on CI.

**Comment by 0-wiz-0** [comment] 2023-06-25 21:35
Thanks for the report.
This is caused by Linux (IMHO bad) decision to re-order command line arguments when using getopt(3).
Should be fixed now, and I'll take a look at the CI.

**Closed** 2023-06-25 21:34 UTC
Labels: bug

**Comment by heirecka** [comment] 2023-06-25 22:15
Confirmed. Thanks for the quick fix!
